FINI-646: Creating a UIKit for reusable shapes
Lombiq/Orchard-UIKit pull request #1
Opened 2021-03-30 13:03 UTC by wAsnk

FINI-646

2021-06-30 13:40 UTC, Piedone commented
Egy új dev branchre mutasson ez inkább.

2021-06-30 13:47 UTC, wAsnk commented
> 
> 
> Egy új dev branchre mutasson ez inkább.

rendicsek

2021-07-05 20:15 UTC, Piedone requested changes

2021-07-05 20:15 UTC, Piedone commented on .gitignore
> +!**/wwwroot/.placeholder
Ilyen fájl nem kellene amúgy?

2021-07-05 20:15 UTC, Piedone commented on Readme.md
> +complex editors.
MD fájlokban nem kell tördelni, mert ott működik a word wrap.

2021-07-05 20:15 UTC, Piedone commented on Manifest.cs
> +[assembly: Feature(
A base feature-nek is kellene egy ilyen, mert most nem lehet az adminról bekapcsolni.

2021-07-05 20:15 UTC, Piedone commented on Readme.md
> +these shapes can be seen at *[Views/ShowCase/ShowCase.cshtml](Views/ShowCase/ShowCase.cshtml)*.
```suggestion
Add the module to your solution and enable the `Lombiq UIKit - Showcase page` feature if you want to check out the currently available shapes. You can see them under `~/UIKitShowCase` after the feature is enabled. The example code for using these shapes can be seen in *[Views/ShowCase/ShowCase.cshtml](Views/ShowCase/ShowCase.cshtml)*.
```

2021-07-05 20:15 UTC, Piedone commented on Readme.md
>  ## Contributing and support
`##` előtt két sortörés kellene.

2021-07-05 20:15 UTC, Piedone commented on Gulpfile.js
> +const gulp = require('gulp');
Az ittenieket alkalmazd légyszi: https://lombiq.atlassian.net/browse/FINI-703

2021-07-05 20:15 UTC, Piedone commented on Gulpfile.js
> +
Fölös sortörés (linter kiírja VS-ben).

2021-07-05 20:15 UTC, Piedone commented on Gulpfile.js
> +gulp.task('default', gulp.parallel('build:styles', 'build:js'));
Ez nem fog lefutni buildkor, mert nincs package.json: https://github.com/Lombiq/NPM-Targets#how-to-use (Ezért nem okoz build errorts sem a dropdownEditor-os ESLint error). És akkor valszeg `node_modules` is kell a gitignore-ba.

2021-07-05 20:15 UTC, Piedone commented on Assets/Scripts/dropdownEditor.js
> +/* It's used from the dropdown shape. */
A disable fölé rakd inkább, és a normáli commentek lehetnek `//`.

2021-07-05 20:15 UTC, Piedone commented on Assets/Scripts/dropdownEditor.js
> +        var lastclass = $('#' + buttonId).attr('class').split(' ').pop();
> Warning	(ESLint) no-var	Unexpected var, use let or const instead.

2021-07-05 20:15 UTC, Piedone commented on Assets/Scripts/textboxEditor.js
> +    $(() => {
Erre van egy fokkal egyszerűbb verzió: https://orcharddojo.net/orchard-resources/CoreLibrary/DevelopmentGuidelines/BestPractices/JavaScript

2021-07-05 20:15 UTC, Piedone commented on Assets/Scripts/dropdownEditor.js
> +function removeSelectedFromDropDown(buttonId) {
JS és CSS fájlokat kötőjeles névvel kellene: dropdown-editor.js.

2021-07-05 20:15 UTC, Piedone commented on Assets/Scripts/textboxEditor.js
> +            if ($(this)[0].value.length === 0) {
Miért nem ez is `$this.val().length`?

2021-07-05 20:15 UTC, Piedone commented on Assets/Scripts/dropdownEditor.js
> +    /* Remove selected. */
E?

2021-07-05 20:15 UTC, Piedone commented on Readme.md
> +This module contains reusable shapes like text editors, custom style checkboxes, dropdown editors, and in the future potentially more
A Gulp Extensions és NPM Targets dependency-t meg kellene említeni.

2021-07-05 20:15 UTC, Piedone commented on Extensions/AttributeExtension.cs
> +        /// For more info see https://stackoverflow.com/questions/8364009/how-to-disable-modelmetadata-isrequired-from-always-being-true-for-non-nullable/17275026
Ezt `<remarks>`-ba kellene.

2021-07-05 20:15 UTC, Piedone commented on Extensions/AttributeExtension.cs
> +        public static bool RequiredAttrExists(this ModelMetadata metaData)
Ne rövidíts szinte soha ("attr").

2021-07-05 20:15 UTC, Piedone commented on Extensions/AttributeExtension.cs
> +        /// Returns true if the given model property has <see cref="RequiredAttribute"/> on it. This is required because
`<see langword="true"/>`, lejjebb is.

2021-07-05 20:15 UTC, Piedone commented on Extensions/AttributeExtension.cs
> +        /// a value type <see cref="ModelMetadata.IsRequired"/> default is true.
Mármint "value type's"?

2021-07-05 20:15 UTC, Piedone commented on Extensions/AttributeExtension.cs
> +            return false;
Ez lehetne egyetlen kifejezés.

2021-07-05 20:15 UTC, Piedone commented on Views/ShowCase/ShowCase.cshtml
> +        new DropdownItem(){ Text = T["Text 1"], DataState = true, DataClass = "btn-success"},
```suggestion
        new DropdownItem { Text = T["Text 1"], DataState = true, DataClass = "btn-success"},
```

Meg a többinél is.

2021-07-05 20:15 UTC, Piedone commented on Views/ShowCase/ShowCase.cshtml
> +        <h4>@T["No label."]</h4>
Ezek címek, szal nem kell pont a végére.

2021-07-05 20:15 UTC, Piedone commented on Views/ShowCase/ShowCase.cshtml
> +        <h4>@T["No label."]</h4>
`<h1>` után nem `<h4>`-nek kellene jönnie.

![image](https://user-images.githubusercontent.com/1976647/124514124-a3779980-dddc-11eb-8dcf-9bcb1b3aa638.png)

2021-07-05 20:15 UTC, Piedone commented on Views/ShowCase/ShowCase.cshtml
> +        <h4>@T["Label top."]</h4>
```suggestion
        <h4>@T["Label on top"]</h4>
```

2021-07-05 20:15 UTC, Piedone commented on TagHelpers/EditorTagHelper.cs
> +        // Otherwise the taghelper can't bind it's value to it.
```suggestion
        // Otherwise the taghelper can't bind its value to it.
```

2021-07-05 20:15 UTC, Piedone commented on Views/UiKit-Editor-Dropdown.cshtml
> +        $(function () {
A dojós módszer kellene itt is.

2021-07-08 12:22 UTC, wAsnk commented on Manifest.cs
> +[assembly: Feature(
Ahha, akkor azért nem lehet. :'D

2021-07-08 12:37 UTC, wAsnk commented on .gitignore
> +!**/wwwroot/.placeholder
Nem tudom, miért kellene?

2021-07-08 13:17 UTC, wAsnk commented on .gitignore
> +!**/wwwroot/.placeholder
Akkó lesz

2021-07-08 13:21 UTC, wAsnk commented on Extensions/AttributeExtension.cs
> +            return false;
Nem tudom mire gondolsz pontosan.

2021-07-08 13:34 UTC, Piedone commented on Extensions/AttributeExtension.cs
> +            return false;
Ez lehet egyetlen boolean expression, nem kellenek az `if`-ek, mert csak egy boolt ad vissza.

2021-07-08 13:58 UTC, wAsnk commented on Views/ShowCase/ShowCase.cshtml
> +        <h4>@T["No label."]</h4>
A h2 túl nagy :((((((

2021-07-08 14:11 UTC, wAsnk commented on Assets/Scripts/textboxEditor.js
> +            if ($(this)[0].value.length === 0) {
Mert itt tökéletesen elfelejtettem ezt.

2021-07-08 14:11 UTC, wAsnk commented on Assets/Scripts/dropdownEditor.js
> +    /* Remove selected. */
E!

2021-07-08 14:20 UTC, Piedone commented on Views/ShowCase/ShowCase.cshtml
> +        <h4>@T["No label."]</h4>
/sad :((

2021-07-09 17:49 UTC, Piedone commented on .gitignore
> +# Exclude node modules
Ez nem egy túl hasznos comment :). Nem szükséges.

2021-07-09 17:49 UTC, Piedone commented on Manifest.cs
> +    Name = "Lombiq UIKit",
Inkább "UI Kit", a másikban is.

2021-07-09 17:49 UTC, Piedone commented on Readme.md
> +these shapes can be seen at *[Views/ShowCase/ShowCase.cshtml](Views/ShowCase/ShowCase.cshtml)*.
Kimaradt.

2021-07-09 17:50 UTC, Piedone commented on Readme.md
>  ## Contributing and support
Kimaradt.

2021-07-09 17:51 UTC, Piedone commented on Gulpfile.js
> +const gulp = require('gulp');
A `watch` task nem úgy van. Lásd még: https://github.com/Lombiq/Gulp-Extensions#tips-for-using-and-naming-multiple-gulp-tasks

2021-07-09 18:02 UTC, Piedone requested changes

2021-07-09 18:02 UTC, Piedone commented on Readme.md
> +- Gulp
Ebből vajon kiderül valakinek, hogy mit kell installálnia :)? Linkek segítenének, ahogy az is, hogy ha nem "Gulp"-ról lenne szó, hanem Gulp Extensionsről.

2021-07-09 18:02 UTC, Piedone commented on Extensions/AttributeExtension.cs
> -        /// For more info see https://stackoverflow.com/questions/8364009/how-to-disable-modelmetadata-isrequired-from-always-being-true-for-non-nullable/17275026
Hosszú sor.

2021-07-09 18:02 UTC, Piedone commented on Extensions/AttributeExtension.cs
> +        /// Returns <see langword="true"/> if the given model property has <see cref="RequiredAttribute"/> on it. This is required because
Hosszú sor.

2021-07-09 18:02 UTC, Piedone commented on Views/ShowCase/ShowCase.cshtml
> +        padding: 1.5em;
Fájlba menjen.

2021-07-09 18:02 UTC, Piedone commented on Manifest.cs
> +    Description = "You can reach the showcase page at /UIKitShowCase"
Ezt kértem a Readme-nél is, itt ugyanúgy helytelen:

```suggestion
    Description = "You can reach the showcase page under /UIKitShowCase."
```

2021-07-09 18:02 UTC, Piedone commented on ShowCase/Controllers/ShowcaseController.cs
> +        public ActionResult ShowCase() => View(model: new ShowcaseViewModel());
Legyen egy UI test, ami ezt legalább megnyitja, a client-side errorokat elkerülendő.

2021-07-09 18:02 UTC, Piedone commented on Views/ShowCase/ShowCase.cshtml
> +@model ShowcaseViewModel
![image](https://user-images.githubusercontent.com/1976647/125118888-9e725d00-e0f0-11eb-89f2-31cc903f11c8.png)

2021-07-09 18:08 UTC, wAsnk commented on Gulpfile.js
> +const gulp = require('gulp');
Szóval itt az lenne a baj, hogy parallel van series helyett és nincs külön egy mindkettőre érvényes sima "watch" task?

2021-07-09 18:08 UTC, wAsnk commented on .gitignore
> +# Exclude node modules
Csak loptam datatablesből :((

2021-07-09 18:10 UTC, wAsnk commented on Views/ShowCase/ShowCase.cshtml
> +        padding: 1.5em;
:(

2021-07-09 18:38 UTC, wAsnk commented on Gulpfile.js
> +const gulp = require('gulp');
Mert ezt amúgy a Finitive.Theme-ből néztem. Azt hittem az jól van megírva.

2021-07-12 11:12 UTC, Piedone commented on Gulpfile.js
> +const gulp = require('gulp');
Aha.

A Finitive.Theme nem tökéletes, a FINI-703 alatt azt is javítani kellene.

2021-07-12 15:51 UTC, Piedone requested changes

2021-07-12 15:51 UTC, Piedone commented on Manifest.cs
> +    Description = "You can reach the showcase page under /UIKitShowCase"
Mivel a showcase egy szó igazából, `/UIKitShowcase` kellene (meg ilyen névvel a controllerben is minden persze). De amúgy is inkonzisztens, mert szerepel "Showcase" és "ShowCase" is.

2021-07-19 18:09 UTC, merged