OSOE-78: UI Kit Showcase UI test
Lombiq/Orchard-UIKit pull request #21
Opened 2022-07-06 15:16 UTC by Luko6

OSOE-78

2022-07-28 16:07 UTC, wAsnk requested changes
I got this while trying to build the solution on a clean repo
![image](https://user-images.githubusercontent.com/19938236/181585685-080663a5-81ee-4c4a-86e6-e06ddf5e9ee1.png)
Could you try building it with a clean repo?

2022-07-28 16:07 UTC, wAsnk commented on .gitignore
> +./Lombiq.UIKit/wwwroot/
Use `**/wwwroot/*` instead.

2022-07-28 16:08 UTC, wAsnk commented
> I got this while trying to build the solution on a clean repo ![image](https://user-images.githubusercontent.com/19938236/181585685-080663a5-81ee-4c4a-86e6-e06ddf5e9ee1.png) Could you try building it with a clean repo?

This doesn't seems to be good:
![image](https://user-images.githubusercontent.com/19938236/181585873-7c883213-1be7-4e3a-87b3-f0d8424a5541.png)

2022-07-28 20:08 UTC, 0liver commented on .gitignore
> +./Lombiq.UIKit/wwwroot/
Why is a change here needed anyway?

2022-07-28 21:35 UTC, Luko6 commented on .gitignore
> +./Lombiq.UIKit/wwwroot/
@wAsnk yes.
@0liver the project was made into a solution with multiple projects, please check it if interested.

2022-07-28 21:38 UTC, Luko6 commented
Builds for me and CI, so the problem must be locally at you, you need the `OSOCE-78-re` branch not `OSOCE-78` that may be a problem.

2022-07-29 12:19 UTC, wAsnk commented
> Builds for me and CI, so the problem must be locally at you, you need the `OSOCE-78-re` branch not `OSOCE-78` that may be a problem.

It's not working here as there are no such modules that you are referencing. It's another thing in the OSOCE repo.

2022-07-29 12:19 UTC, wAsnk commented
You have conflicts here and in the OSOCE PR.

2022-07-29 16:52 UTC, Luko6 commented
Ok I understand your comment now. If you try to build the `dev` branch here, the same problem comes up. If you check [Chart.js](https://github.com/Lombiq/Orchard-Chart.js) which has a similar structure to this module, the same happens again. This is not meant for standalone builds, and OSOCE is an example on how this should be used, this is even documented in the Readme.

2022-07-29 16:55 UTC, wAsnk commented
> Ok I understand your comment now. If you try to build the `dev` branch here, the same problem comes up. If you check [Chart.js](https://github.com/Lombiq/Orchard-Chart.js) which has a similar structure to this module, the same happens again. This is not meant for standalone builds, and OSOCE is an example on how this should be used, this is even documented in the Readme.

This is soooo ugly. 😅 But I accept it. 
Could you just add to the readme where those dependencies should be placed exactly if not the NuGet versions are used?

2022-07-29 17:41 UTC, wAsnk commented
I get this error when I run the default task in the Lombiq.UIKit:
![image](https://user-images.githubusercontent.com/19938236/181815174-99d83d5a-fc74-49db-879b-b17c38715e93.png)
Am I doing something wrong again? :D

2022-07-29 17:43 UTC, wAsnk commented
When I'm using the bootstrap dropdown buttons, the dropdown can't be closed:
![image](https://user-images.githubusercontent.com/19938236/181815437-0274387c-3590-488c-92ae-b62e2ee25fad.png)

2022-08-01 18:12 UTC, Piedone commented on Lombiq.UIKit.Tests.UI/License.md
> +Copyright © 2021, [Lombiq Technologies Ltd.](https://lombiq.com)
Use the updated license files from the root in all cases.

2022-08-07 19:41 UTC, Piedone commented
Add "Fixes #8" to the PR description to automatically close the related issue.

2022-09-15 09:06 UTC, wAsnk approved these changes

2022-09-15 09:06 UTC, merged