OSOE-920: Create a reusable widget for the carousel in Lombiq.UIKit
Lombiq/Orchard-UIKit pull request #69
Opened 2024-12-20 23:16 UTC by milosh-96

OSOE-920

2025-01-13 12:04 UTC, barthamark requested changes

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets.Tests.UI/Extensions/TestCaseUITestContextExtensions.cs
> +        bool showDots = false;
You can make these const.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets.Tests.UI/Readme.md
> +# Lombiq UI Kit for Orchard Core - UI Test Extensions
Isn't it specifically for the widgets?

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets.Tests.UI/Lombiq.UIKit.Widgets.Tests.UI.csproj
> +    <RepositoryUrl>https://github.com/Lombiq/Orchard-Chart.js</RepositoryUrl>
Update the URL.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Migrations/CarouselWidgetMigrations.cs
> +            );
Fix the indentation.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Migrations/CarouselWidgetMigrations.cs
> +                part.WithField(part => part.Title, field => field.WithPosition("0"));
Why do you have a field for the Title instead of using `TitlePart`? Not necessarily bad just asking if you have a specific reason.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Migrations/CarouselWidgetMigrations.cs
> +        );
Indent.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Migrations/CarouselWidgetMigrations.cs
> +        await _contentDefinitionManager.AlterTypeDefinitionAsync("Slide", type =>
Use constants for the content type names here and for the CarouselWidget as well so you can reference them elsewhere in the code like here in ln48.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Models/CarouselWidgetPart.cs
> +public class CarouselWidgetPart : ContentPart;
Leave an empty line above please.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Migrations/CarouselWidgetMigrations.cs
> +            ).Stereotype(CommonStereotypes.Widget));
Indent.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Models/SlidePart.cs
> +public class SlidePart : ContentPart
Leave an empty line above please.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Settings/CarouselWidgetPartSettings.cs
> +    public string Options { get; set; } = DefaultValues.CarouselWidgetPartOptions;
Rename it to `OptionsJsonSerialized` instead so it's clear that the expected value is a JSON. You can also add an `Options` getter or `GetOptions` method that will return the deserialized JSON (if needed at all, if not, then it's not important).

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Settings/CarouselWidgetPartSettingsDisplayDriver.cs
> +public class CarouselWidgetPartSettingsDisplayDriver : ContentTypePartDefinitionDisplayDriver<CarouselWidgetPart>
It's odd that you have several classes where you don't have an empty line between the namespace and class, please check your other files to make it consistent.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Settings/CarouselWidgetPartSettingsDisplayDriver.cs
> +            m => m.Options
Don't use abbreviations as lambda properties.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Settings/CarouselWidgetPartSettingsViewModel.cs
> +    public string? Options { get; set; }
Same rename.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Views/Home/Index.cshtml
> +﻿Template
I think it's not needed.

2025-01-13 12:04 UTC, barthamark commented on Lombiq.UIKit.Widgets/Views/Widget-CarouselWidget.cshtml
> +           AdditionalClasses="slickCarouselSample"
Why adding this class with `sample` text? From what I understand it's a final shape for the widget so it shouldn't be a sample but the actually shape. Maybe you wanted to add `carouselWidget__widget`?

2025-01-13 13:05 UTC, milosh-96 commented on Lombiq.UIKit.Widgets/Settings/CarouselWidgetPartSettingsDisplayDriver.cs
> +public class CarouselWidgetPartSettingsDisplayDriver : ContentTypePartDefinitionDisplayDriver<CarouselWidgetPart>
Visual Studio "X references" always confuses me so that's why I have this much errors. Visually they are separated, but in code they aren't.

2025-01-16 12:35 UTC, barthamark requested changes

2025-01-16 12:35 UTC, barthamark commented on Lombiq.UIKit.Widgets/Constants/ContentTypes.cs
> +    public const string Slide = "Slide";
You can use `nameof` here and below.

2025-01-16 12:35 UTC, barthamark commented on Lombiq.UIKit.Widgets/Handlers/SlidePartHandler.cs
> +        Task.Run(() => context.ContentItem.DisplayText = part.ContentItem.Content.TitlePart.Text);
This is not necessary. The TitlePart's functionality already do this.

2025-01-16 12:35 UTC, barthamark commented on Lombiq.UIKit.Widgets/Constants/ContentTypes.cs
> +    public const string SlidePart = nameof(SlidePart);
Part names are not content types. You can keep reference them as `nameof(PartName)` so you don't need consts for these.

2025-01-16 12:35 UTC, barthamark commented on Lombiq.UIKit.Widgets/Views/Widget-CarouselWidget.cshtml
> +        bagItems.ForEach(async (slide) => items.Add(await New.Slide(Title: slide.ContentItem.Content.TitlePart.Text, Image: slide.Image.Paths[0])));
You can rely on the `slide.ContentItem.DisplayText`.

2025-01-17 17:50 UTC, barthamark requested changes
Make sure the carousel is usable if you do this:
1. Setup the website using the SaaS recipe.
2. Run the Sample Carousel recipe.

Check if the page is imported, features are enabled, images are displayed, etc.

2025-01-17 17:50 UTC, barthamark commented on Lombiq.UIKit.Widgets/Constants/ContentTypes.cs
> +    public const string SlidePart = nameof(SlidePart);
The `SlidePart` is still here.

2025-01-17 17:50 UTC, barthamark commented on Lombiq.UIKit.Widgets/Manifest.cs
> +)]
Add the following dependencies: Lombiq.UIKit (use an appropriate const from the module), OrchardCore.ContentFields, OrchardCore.Media.

2025-01-17 17:50 UTC, barthamark commented on Lombiq.UIKit.Widgets/Manifest.cs
> +)]
Add an appropriate category.

2025-01-17 17:50 UTC, barthamark commented on Lombiq.UIKit.Widgets/Recipes/Lombiq.UIKit.Widgets.Content.recipe.json
> +    "training",
You can leave out the training.

2025-01-17 17:50 UTC, barthamark commented on Lombiq.UIKit.Widgets/Recipes/Lombiq.UIKit.Widgets.Content.recipe.json
> +                            "about-bg.jpg"
These images won't be loaded because these are not part of the recipe so won't be imported. Add a media step where you also upload these images and make them part of the repo as well.

2025-01-17 17:50 UTC, barthamark commented on Lombiq.UIKit.Widgets/Recipes/Lombiq.UIKit.Widgets.Content.recipe.json
> +        "Lombiq.UIKit.Widgets"
Also enable the Helpful Content Types feature because the Page content type won't be loaded otherwise.

2025-01-18 06:43 UTC, barthamark approved these changes

2025-01-18 06:43 UTC, merged