FOLK-152: Additional improvements
Lombiq/Orchard-UIKit pull request #9
Opened 2022-03-04 13:30 UTC by porgabi

[FOLK-152](https://lombiq.atlassian.net/browse/FOLK-152)

2022-03-04 13:39 UTC, Piedone commented
Please use a descriptive title.

2022-03-23 16:24 UTC, barthamark requested changes

2022-03-23 16:24 UTC, barthamark commented on Views/UiKit-Editor-Textbox.cshtml
> +    var hasAsteriskInPlaceholder = Model.LabelPosition == LabelPosition.None && isRequired;
Why can't you have an asterisk in the placeholder in other positions?

2022-03-24 15:15 UTC, porgabi commented on Views/UiKit-Editor-Textbox.cshtml
> +    var hasAsteriskInPlaceholder = Model.LabelPosition == LabelPosition.None && isRequired;
Not sure, that part I did not touch.

2022-03-30 18:27 UTC, merged